dev:
  resourceGroup: RG-NEXTOPS-POC-GLOBAL-001
  aksCluster: ${{ values.projectName }}-dev-aks
  acaEnvironment: ${{ values.projectName }}-dev-env
  namespace: ${{ values.projectName }}-dev

stage:
  resourceGroup: RG-NEXTOPS-POC-GLOBAL-001
  aksCluster: ${{ values.projectName }}-stage-aks
  acaEnvironment: ${{ values.projectName }}-stage-env
  namespace: ${{ values.projectName }}-stage

prod:
  resourceGroup: RG-NEXTOPS-POC-GLOBAL-001
  aksCluster: ${{ values.projectName }}-prod-aks
  acaEnvironment: ${{ values.projectName }}-prod-env
  namespace: ${{ values.projectName }}-prod
