apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secret
  labels:
    backstage.io/kubernetes-id: {{ .Release.Name }}

type: Opaque

stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: "{{ $value }}"
{{- end }}
