dev:
  resourceGroup: rg-nextops-adv-dev
  aksCluster: nextops-adv-dev-aks
  namespace: nextops-adv-dev

stage:
  resourceGroup: rg-nextops-adv-stage
  aksCluster: nextops-adv-stage-aks
  namespace: nextops-adv-stage

prod:
  resourceGroup: rg-nextops-adv-prod
  aksCluster: nextops-adv-prod-aks
  namespace: nextops-adv-prod
